### PR TITLE
fixed NPE

### PR DESCRIPTION
**Pull request by FlorianMichael**

### CODE REVIEW

**Comment by Flourick** [comment]
Under what circumstances does it happen?

**Comment by FlorianMichael** [comment]
If the Ridden Entity is null, Minecraft has this check as well

**Comment by FlorianMichael** [comment]
I don't know myself when it happens, but my game crashed often because of the code, and since Minecraft has the query too, you should make it too

**Comment by Flourick** [comment]
It already checks for `livingEntity` null via the `riddenEntityHearts` not equal zero check so additional null check is not needed and in the case it is null vanilla handles it. This also potentionally breaks autohide hotbar feature. Your game had to crash for a different reason.

**Comment by FlorianMichael** [comment]
The logs are pretty clear, but well, your choice

**Pull request closed without merging**
